# crates/bigint/Cargo.toml
[package]
name = "bigint"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.5"  # For benchmarking
proptest = "1.0"   # For property-based testing